require 'fileutils'
require 'yaml'

add_extra_platforms(
  platforms: [:windows],
  platforms: [:linux]
)

default_platform(:android)

def fetch_current_version
    YAML.safe_load(File.read('../pubspec.yaml'))['version']
end

def fetch_versions
  path = "../CHANGELOG.md"
  content = File.read(path)
  regex = /## \[(.+\+\d+)\]/
  content.scan(regex).map(&:first)
end

platform :android do
  desc "Ensures flutter is installed"
  lane :bootstrap do
    flutter_bootstrap(
      flutter_channel: 'stable',
      android_licenses: {
        'android-sdk-license' => '24333f8a63b6825ea9c5514f83c2829b004d1fee',
      },
    )
  end

  desc "Build apk file"
  lane :build do
    flutter_build(build: 'apk')
  end

  desc "Build aab file"
  lane :build_aab do
    flutter_build(build: 'appbundle')
  end

  desc "Writes playstore changelogs from CHANGELOG.md"
  lane :changelog do
    sh("dart pub global activate cider")
    versions = fetch_versions
    versions.each do |version|
      if version == 'Unreleased'
        next
      end
      build_number = version.split('+').last
      description = sh("cider describe --only-body #{version}")
      changelogs = "./metadata/android/en-US/changelogs"
      FileUtils.mkdir_p(changelogs)
      File.open("#{changelogs}/#{build_number}.txt", 'w') do |file|
        file.write(description)
      end
    end
  end

  desc "Uploads appbundle to playstore"
  lane :upload do |options|
    build_number = fetch_current_version.split("+")[1].to_i
    upload_to_play_store(
      aab: "build/app/outputs/bundle/release/app-release.aab",
      version_code: build_number,
      skip_upload_apk: true,
      validate_only: options[:validate_only].to_s == 'true',
    )
  end

  desc "Build appbundle and upload to playstore"
  lane :deploy do
    build_aab
    changelog
    upload
  end
end

platform :ios do
  desc "Ensures flutter is installed"
  lane :bootstrap do
    flutter_bootstrap(flutter_channel: 'stable')
  end

  desc "Build ios archive"
  lane :build do
    flutter_build(
        build_args: ['--no-codesign'],
        build: 'ios',
    )
  end

  desc "Package ios archive into ipa"
  lane :package_release do
    Dir.chdir("build/ios/iphoneos") do
      sh("mkdir Payload")
      sh("mv Runner.app Payload/Runner.app")
      sh("zip -9 -r Runner.ipa Payload")
    end
  end
end

platform :windows do
  desc "Ensures InnoSetup is installed"
  lane :bootstrap do
    sh(
      "winget install --id JRSoftware.InnoSetup --silent --accept-package-agreements --accept-source-agreements --no-upgrade",
      error_callback: proc { |result, return_code|
        # APPINSTALLER_CLI_ERROR_PACKAGE_ALREADY_INSTALLED
        if return_code == -1978335135
          true
        else
          false
        end
      }
    )
  end

  desc "Builds an exe installer with fastforge and InnoSetup"
    lane :build do
      sh("flutter pub global activate fastforge")
      Dir.chdir("../") do
        sh("fastforge package --platform=windows --targets=exe --skip-clean")
      end
    end
end

platform :linux do
  desc "build package"
  lane :build do
      flutter_bootstrap(flutter_channel: 'stable')
      sh("DESTDIR='' flutter build linux --release")
  end

  desc "install linux package"
  lane :install do
    Dir.chdir("../")
    FileUtils.mkdir_p("#{ENV['DESTDIR']}/opt/e1547")
    FileUtils.mkdir_p("#{ENV['DESTDIR']}/usr/bin")
    FileUtils.mkdir_p("#{ENV['DESTDIR']}/usr/share/icons/hicolor/scalable/apps/")

    sh("cp -rv build/linux/x64/release/bundle/* #{ENV['DESTDIR']}/opt/e1547")
    sh("ln -s /opt/e1547/e1547 #{ENV['DESTDIR']}/usr/bin/e1547")
    sh("chmod 0755 #{ENV['DESTDIR']}/opt/e1547/e1547")
    sh("install -Dm644 assets/icon/desktop/round.ico #{ENV['DESTDIR']}/usr/share/icons/hicolor/scalable/apps/e1547.ico")
    sh("install -Dm644 assets/static/e1547.desktop '#{ENV['DESTDIR']}/usr/share/applications/e1547.desktop'")
  end

  desc "package debian"
  lane :pkgdeb do

    Dir.chdir("../")
    FileUtils.mkdir_p("#{ENV['DESTDIR']}/DEBIAN")
    APPVER=sh("grep -i -e \"version: \" pubspec.yaml | awk -F' ' '\{print $2\}' /dev/stdin").strip
    CONTROL=sh("sed 's/APPVER/#{APPVER}/g' fastlane/debian-control > #{ENV['DESTDIR']}/DEBIAN/control")

    FileUtils.mkdir_p("dist/linux")
    sh("dpkg-deb --root-owner-group --build #{ENV['DESTDIR']}")
    sh("mv #{ENV['DESTDIR']}.deb dist/linux/e1547-#{APPVER}.deb")
  end
end